### ISSUE TITLE
Symbol.iterator compatibility

### ISSUE THREAD

**Issue by barberboy** [es-shims/es-shim-api#1]
Could you also include guidance for `Symbol.iterator` usage for shims that want to be compatible with the ES Shim API. This is needed for interoperability between Set/Map/etc. collections and Array.from/for...of.

For instance, if I'm writing a Set or Map implementation, what property name do I use for the `.values()`, `.keys()`, and `.entries()` iterators if `Symbol.iterator` is not present? [core-js](https://github.com/zloirock/core-js/blob/v1.1.1/modules/%24.wks.js#L5) and [es6-shim](https://github.com/paulmillr/es6-shim/blob/0.33.1/es6-shim.js#L277) use their own internal string as a fallback, which means that users couldn't use their `Array.from()` shim with my `Set` implementation unless the user [shims `Symbol.iterator` into the global environment](medikoo/es6-symbol) before loading both `Array.from` and my `Set` implementation.

I like the convenience of standardizing on using the string `"@@iterator"` as the fallback property name if `Symbol.iterator` is not defined, but that may not be realistic or desired. [core-js checks for it](https://github.com/zloirock/core-js/blob/v1.1.1/modules/core.get-iterator-method.js#L5) when retrieving the iterator for `Array.from` and `for...of`, but doesn't use it as a fallback for the iterator property in its collections. The way [es6-shim checks for it](https://github.com/paulmillr/es6-shim/blob/0.33.1/es6-shim.js#L281) does not work in a general way.

Do we avoid any compatible fallback value and just require the user to shim `Symbol.iterator` globally if they want to use `Array.from` and iterable collections from different modules? If the user calls our `require('foo').shim` do we also shim `Symbol.iterator` into global as a convenience (I recommend no)? When implementing an Iterable object, what property name should we fall back to if `Symbol.iterator` isn't available ("@@iterator" is the only thing that makes sense), or should we not even bother (this makes sense, but also makes me sad).

**Comment by ljharb** [comment]
Very good question.

Clearly if `typeof Symbol === 'function' && typeof Symbol.iterator === 'symbol'` then that should be used.

Symbols can not be reliably shimmed, however, so it's not possible to shim it globally.

`'@@iterator'` was the actual value in older Firefox versions, which is why the es6-shim uses it.

I'm not really sure what the best solution is here - it will require some thought.

**Comment by ljharb** [comment]
I've published https://npmjs.com/es-get-iterator - if you use that package on an iterable, you will get an iterator object in every possible environment I'm aware of.

https://npmjs.com/iterate-value uses that to give you an iteration construct - provide a callback for "forEach", or omit one to collect the values in an array.
