### ISSUE TITLE
Fix badges?

### ISSUE THREAD

**Issue by jcbhmr** [es-shims/es-shim-api#27]
Right now some of the badges in the readme are broken. This doesn't look good as a potential user of @es-shims lol. I think it would be a good idea to fix them. 😉

![image](https://github.com/es-shims/es-shim-api/assets/61068799/aa1787a2-18ab-49b2-ba1d-b0d8bdcc0ca2)

**Comment by ljharb** [comment]
I'll remove the david.dm ones, but the other one works, it's just that rate limited responses get cached unfortunately.
