### ISSUE TITLE
Guidance on how to consume in a browser

### ISSUE THREAD

**Issue by JakeChampion** [es-shims/es-shim-api#3]
I was thinking about how to enable these polyfills to work in a browser without requiring a build-step. What do you think about providing each file {implementation, index, polyfill, shim} in UMD format?

**Comment by ljharb** [comment]
Why would a build step not be desired?

I'm not really a fan of UMD - if you're using AMD or CJS, you'll use a build step, and if you're including it in a script tag, you're not using modern web dev practices.

What's the use case?

**Comment by JakeChampion** [comment]
My particular use-case is to include these polyfills into polyfill.io without having to require a build-step. Maybe a link in the readme which informs the reader about services such as wzrd.in & npmcdn.com would suffice?

**Comment by ljharb** [comment]
Sure, PRs for documentation tweaks are always welcome.

**Comment by ljharb** [comment]
Closing this for now - please feel free to PR documentation changes in to help users stuck on ancient build systems.
