### ISSUE TITLE
Should require('foo') return a native implementation if it exists?

### ISSUE THREAD

**Issue by glenjamin** [es-shims/es-shim-api#4]
From the docs

> is a spec-compliant JS function

This is a little unclear to me, does it have to be a pure JS impl, or just an impl that will run correct on a JS runtime?

**Comment by ljharb** [comment]
If you want "native if it exists", you want `require('foo/polyfill')()` or `require('foo').getPolyfill()`.

Currently, I use the pure JS implementation for the default export - although it makes sense to use the "polyfill" method instead. I'll leave this open until I decide to mandate that.

**Comment by ljharb** [comment]
Thanks, I've changed the requirement.
